name: Deploy beta for Android

on:
  push:
    branches:
      - master
      - release/*
      
jobs:
  build-android:
    name: Deploy beta version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo /home/cirrus/sdks/flutter/bin/flutter pub get
      - name: Build Android version
        run:  sudo /home/cirrus/sdks/flutter/bin/flutter build apk --release
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: /android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
