name: Deploy beta for Android

on:
  push:
    branches:
      - master
      - release/*
      
jobs:
  build-android:
    name: Deploy beta version

    runs-on: ubuntu-latest

    container:
      image:  dumazy/flutter:latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Android version
        run:  flutter build apk --pub --release --verbose
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        id: sign_release
        with:
          releaseDirectory: build/app/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Store APK as artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: ${{ steps.sign_release.outputs.signedReleaseFile }}
