name: Deploy beta for Android

on:
  push:
    branches:
      - master
      - release/*
      
jobs:
  login-docker:
    name: Login to Github Packages Docker
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        run: echo "Login as $GITHUB_ACTOR" && docker login -u $GITHUB_ACTOR -p ${{secrets.DOCKER_PACKAGES_TOKEN}} docker.pkg.github.com
    
  build-android:
    needs: login-docker
    name: Deploy beta version

    runs-on: ubuntu-latest

    container:
      image:  docker.pkg.github.com/dumazy/docker-flutter/flutter:1.0.0

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: echo "Login as $GITHUB_ACTOR" && docker login -u $GITHUB_ACTOR -p ${{secrets.DOCKER_PACKAGES_TOKEN}} docker.pkg.github.com
      - name: Build Android version
        run:  flutter build apk --pub --release --verbose
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        id: sign_release
        with:
          releaseDirectory: build/app/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: ${{ steps.sign_release.outputs.signedReleaseFile }}
