name: Flutter Unit tests

on: [push]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:v1.12.13-hotfix.5

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo /home/cirrus/sdks/flutter/bin/flutter pub get
    - name: Run tests
      run: sudo /home/cirrus/sdks/flutter/bin/flutter test
